In [1]:
import numpy as sai
a=sai.array([1,2,3])
print(a)

[1 2 3]


In [50]:
import numpy as sai
p=sai.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [22]:
import numpy as sai
b=sai.zeros((5,6))
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
import numpy as sai
c=sai.full((5,6),18)
print(c)

[[18 18 18 18 18 18]
 [18 18 18 18 18 18]
 [18 18 18 18 18 18]
 [18 18 18 18 18 18]
 [18 18 18 18 18 18]]


In [24]:
import numpy as sai
d=sai.random.random((5,6))
print(d)

[[0.42791357 0.69942778 0.00752823 0.80921024 0.05412845 0.24593363]
 [0.44404745 0.03263631 0.38366438 0.90032046 0.60656079 0.20836875]
 [0.73306875 0.9577108  0.49982528 0.65826603 0.24265423 0.29715254]
 [0.64429467 0.62820091 0.57870142 0.15199779 0.3625315  0.29555197]
 [0.68794544 0.86197368 0.01907898 0.02409137 0.78560739 0.82374034]]


In [61]:
import numpy as sai
e=p.reshape(3,5)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [38]:
import numpy as sai
a=sai.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print(p.ndim)

2


In [63]:
print(p.size)

15


In [41]:
print(a.dtype)

int32


In [64]:
b=p.astype('f')
print(b)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [44]:
c=b.astype('i')
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
import numpy as sai
a=sai.array([1,2,3])
print(a)

[1 2 3]


In [53]:
import numpy as sai
p=sai.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [54]:
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


In [55]:
print(p[2,0:2])

[7 8]


In [56]:
print(p[2:,2:])

[[ 9]
 [12]
 [15]]


In [57]:
print(p[3:,3:])

[]


In [58]:
print(p[:,1])

[ 2  5  8 11 14]
