In [13]:
import numpy as np 
arr=np.array([[3,6,9,1],
              [6,-0.6,8,9],
             [4.8,1,0.1,8],
             [4,7,-9,4.0]])
print(arr)

[[ 3.   6.   9.   1. ]
 [ 6.  -0.6  8.   9. ]
 [ 4.8  1.   0.1  8. ]
 [ 4.   7.  -9.   4. ]]


In [9]:
print(arr[0:3:2])

[list([3, 6, 9, 1]) list([4.8, 1, 0.1, 8])]


In [14]:
temp=arr[:1,:2]
print(temp)

[[3. 6.]]


In [17]:
temp=arr[[0,3,1,2],[1,0,3,2]]
print(temp)
cond=arr>2
temp=arr[cond]
print(temp)

[6.  4.  9.  0.1]
[3.  6.  9.  6.  8.  9.  4.8 8.  4.  7.  4. ]


In [18]:
arr=np.array([2,6,8,4,5,0,9])
print(arr)
print(arr[::5])

[2 6 8 4 5 0 9]
[2 0]


In [19]:
arr1=np.array([3,7,6])
arr2=np.array([2,9,3])
arr=np.concatenate((arr1,arr2))
print(arr1,arr2)
print(arr)

[3 7 6] [2 9 3]
[3 7 6 2 9 3]


In [20]:
arr=np.vstack((arr1,arr2))
print(arr)

[[3 7 6]
 [2 9 3]]


In [21]:
arr=np.dstack((arr1,arr2))
print(arr)


[[[3 2]
  [7 9]
  [6 3]]]


In [22]:
arr=np.array([2,6,8,4,5,0,9])
newarr=np.array_split(arr,5)
print(newarr)

[array([2, 6]), array([8, 4]), array([5]), array([0]), array([9])]
