In [2]:
import numpy as np
arr1=[20,40,50,70,10]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))
sclr=3
print("Scalar value:",sclr)
print("Array:",a)
print("Result:",a*sclr)


[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]
1150
Scalar value: 3
Array: [20 40 50 70 10]
Result: [ 60 120 150 210  30]


In [3]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,7,2]
arr2=[6,5,3]
vect_func=np.vectorize(my_func)
print("Array1:",arr1)
print("Array2:",arr2)
print("Result:",vect_func(arr1,arr2))

Array1: [10, 7, 2]
Array2: [6, 5, 3]
Result: [4 2 5]
